<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RollForward>LatestMajor</RollForward>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="NekoT.Tests" />
    <InternalsVisibleTo Include="NekoT.Desktop" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Clowd.Squirrel" Version="3.0.210-g5f9c594" />
    <PackageReference Include="Microsoft.Data.Sqlite" Version="8.0.5" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="8.0.0" />
    <PackageReference Include="System.Security.Cryptography.ProtectedData" Version="8.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\NekoT.Models\NekoT.Models.csproj" />
  </ItemGroup>

</Project>
